# Generated by Django 5.1.4 on 2024-12-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='image_3',
        ),
    ]
