# Generated by Django 5.1.4 on 2024-12-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_image1_product_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='state_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
